FROM tensorflow/tensorflow:2.0.0-gpu-py3-jupyter

WORKDIR /app

ADD requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

VOLUME /tf/code

CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=abcd"]
