version: '2.3'
services:
    tensorflow_gpu:
        image: tensorflow-gpu
        runtime: nvidia
        volumes:
            - /home/thusitha/work/bigdata/datasets:/datasets

    tensorflow_gpu_jupyter:
        image: tensorflow-gpu-jupyter
        runtime: nvidia
        ports:
            - "8888:8888"
        volumes:
            - ./notebooks:/tf/code
            - /home/thusitha/work/bigdata/datasets:/datasets
        #user: "1000:1"